AliveTeam/alive_reversing

Source/AliveLib/Abe.cpp
Moving Abe left and right repeated same code, making the method "Abe::ToLeftRightMovement_44E340()" unnecessarily long. This version controls the movement direction using an auxiliary variable "directionX", allowing a single code segment to handle both the left and right movements.
=> Removed unnecessary repetition in Abe::ToLeftRightMovement_44E340()

Source/AliveLib/GasCountDown.cpp
Fixes this issue: https://github.com/AliveTeam/alive_reversing/issues/312
The gas timer was able to become negative after a quikload, causing the game to crash. The timer could become negative also in the original implementation, but without a crash. Adding this simple check seems to fix the problem.
=> Fix to the gas timer bug

Source/AliveLib/Explosion.cpp
Fixes this issue: https://github.com/AliveTeam/alive_reversing/issues/335
The stand alone version assigned `word_5C1BB6` to 0 whereas the actual value in 0x5C1BB6 is 1 (used by the hook version). This constant determines the value of `ScreenShake::field_42` which determines whether an event broadcasts of type `kEventScreenShake` is triggered which leads to the knockbacks.
=> A fix to the explosion knockback bug

Source/AliveLib/Scrab.cpp
+ ScrabSound logging removal
Enums weren't used everywhere they should, so I fixed that.
Also, still missing naming for `sub_states` `13` & `15` of `AI_ChasingEnemy`, but as it seems they can't be called, that'll do it for now.
=> Scrab enums update

Source/AliveLibAE/Abe.cpp, Source/AliveLibAE/Game.cpp, Source/AliveLibAE/LiftPoint.cpp, Source/AliveLibAE/Paramite.cpp, Source/AliveLibAE/PauseMenu.cpp, Source/AliveLibAE/PauseMenu.hpp, Source/AliveLibAE/PlatformBase.cpp, Source/AliveLibAE/PlatformBase.hpp, Source/AliveLibAE/Psx.cpp, Source/AliveLibAE/Psx.hpp, Source/AliveLibAE/PsxDisplay.cpp, Source/AliveLibAE/PsxDisplay.hpp, Source/AliveLibAE/PsxRender.cpp, Source/AliveLibAE/PullRingRope.cpp, Source/AliveLibAE/PullRingRope.hpp, Source/AliveLibAE/TrapDoor.cpp, Source/AliveLibAO/OrbWhirlWind.cpp, Source/AliveLibAO/OrbWhirlWind.hpp, Source/AliveLibAO/OrbWhirlWindParticle.cpp, Source/AliveLibAO/OrbWhirlWindParticle.hpp
Named fields, flags and functions in PauseMenu, PlatformBase, Psx, PsxDisplay, (a bit of) PsxRender and PullRingRope classes. Also changed variable names in AO's OrbWhirlWind and OrbWhirlWindParticle classes to match their AE counterparts.
=> Named fields, flags and functions in more classes. Matched AO's OrbWhirlWind and OrbWhirlWindParticle classes to AE counterparts.

Source/AliveLibAE/CMakeLists.txt, Source/AliveLibAE/Factory.cpp, Source/AliveLibAE/SlogHut.hpp, Source/AliveLibAE/Slurg.cpp, Source/AliveLibAE/Slurg.hpp, Source/AliveLibAE/SlurgSpawner.cpp, Source/AliveLibAE/SlurgSpawner.hpp
Moved `SlurgSpawner` class to its own set of files. Named fields and structures in the `SlogHut`, `Slurg` and `SlurgSpawner` classes.
=> Moved SlurgSpawner class to its own set of files. Named fields and structures in the SlogHut, Slurg and SlurgSpawner classes.

Source/AliveLibAE/Sys.cpp, Source/AliveLibAE/VGA.cpp
This commit fixes rounding error when maintaining aspect ratio, and improves rendering on Retina Macs by enabling high DPI support in SDL.
=> Fix rounding errors, improve rendering on high DPI displays

Source/AliveLibAE/Slig.cpp
previously this could crash the game:
=> fix another slig crash

Source/AliveLibAE/Abe.cpp, Source/AliveLibAE/Abe.hpp, Source/AliveLibAE/Alarm.cpp, Source/AliveLibAE/Alarm.hpp, Source/AliveLibAE/BaseAliveGameObject.cpp, Source/AliveLibAE/BaseAliveGameObject.hpp, Source/AliveLibAE/Bone.cpp, Source/AliveLibAE/Electrocute.cpp, Source/AliveLibAE/Fleech.cpp, Source/AliveLibAE/FlyingSlig.cpp, Source/AliveLibAE/GameEnderController.cpp, Source/AliveLibAE/GameEnderController.hpp, Source/AliveLibAE/Glukkon.cpp, Source/AliveLibAE/Grenade.cpp, Source/AliveLibAE/LaughingGas.cpp, Source/AliveLibAE/LaughingGas.hpp, Source/AliveLibAE/Meat.cpp, Source/AliveLibAE/MineCar.cpp, Source/AliveLibAE/Mudokon.cpp, Source/AliveLibAE/NakedSlig.cpp, Source/AliveLibAE/Paramite.cpp, Source/AliveLibAE/PauseMenu.cpp, Source/AliveLibAE/QuikSave.cpp, Source/AliveLibAE/Rock.cpp, Source/AliveLibAE/Scrab.cpp, Source/AliveLibAE/Shrykull.cpp, Source/AliveLibAE/SlapLock.cpp, Source/AliveLibAE/Slig.cpp, Source/AliveLibAE/Slog.cpp, Source/AliveLibAE/Teleporter.cpp
- Named last flag in the `Abe` class.
- Named a couple of unnamed arguments in `Alarm::ctor_4091F0()`.
- Fixed alignment of the switch-case statement in `Alarm::vUpdate_409460()`.
- Named fields and flags in the `BaseAliveGameObject` class.
- Fixed alignment of switch-case statements in the `BaseAliveGameObject` class.
- Named states in the `GameEnderController` class.
- Named some fields in the `LaughingGas` class.
=> Named Variables in the Alarm, BaseAliveGameObject, GameEnderController and LaughingGas Classes

Source/AliveLibAO/Slig.cpp
If a possessed Slig stands in the same position as a lever and attempt to use it, he will make a high pitch squeak instead of saying "What?". This PR fixes the issue.
Really awesome project by the way 👍
=> Fix slig squeaking when saying "What" while standing in front of lever

Source/AliveLibAE/Scrab.cpp, Source/AliveLibAE/Slig.cpp
as mentioned in the issue #1017 in OG the scrab apparently tries to kick abe (just sometimes depending on where the scrab was standing). this adds the original behavior back with the leg kicking. this doesn't fix the OG bug where the scrab tries to run towards abe through the wall. #1017 should now be labelled with the OG bug label instead (and perhaps remove the note?).
=> fix wrong scrab behavior

Source/AliveLibAO/Factory.cpp, Source/AliveLibAO/Factory.hpp, Source/AliveLibAO/LiftMover.cpp, Source/AliveLibAO/Map.cpp, Source/AliveLibAO/Map.hpp, Source/AliveLibAO/ResourceManager.cpp, Source/AliveLibAO/ResourceManager.hpp
apparently the game throws pretty quick "resource not loaded" dunno if i just mess up somewhere or if the game is actually scuffed maybe you can check paul
=> ALIVE_FATAL on resources that are not loaded part 2, add LoadMode enum

Source/AliveLibAE/Input.cpp, Source/AliveLibAE/Input.hpp, Source/AliveLibAE/MainMenu.cpp, Source/AliveLibAO/Input.cpp, Source/AliveLibAO/Input.hpp, Source/AliveLibAO/MainMenu.cpp, Source/AliveLibAO/PauseMenu.cpp, Source/AliveLibAO/StringFormatters.cpp
Also includes:
- decoupling of Speak I/II from Sneak/Run
- introduction of a Pause input command
- renames, some explaining comments
Known bugs to be raised later:
- OG: when in keyboard remap mode, Speak I and II can be bound to
- OG: with keyboard as active controller, RF zulag 1 [screen: R1P16C02] LCD string with chanting hint cannot be looked up properly (OG: says `Chant by holding alt and shift.`), now with these changes it displays blanks `Chant by holding  and .`
=> AO controller support

Source/AliveLibAO/Slog.cpp
should prevent out of bounds array crashes
=> fix sSlogStopRunningVelX_4BCCC8 and add strange missing 32000 entries

CMakeLists.txt
Running `CMake -> Build All` failed with error `invalid option: /bigobj`
I was able to resolve this by replacing `add_definitions(/bigobj)` with `add_compile_options(/bigobj)`.
I suggest testing on your local systems. I am running 
* VC 2017 Community - 15.9.34
* .NET Framework 4.8.04084
=> replace add_definitions(/bigobj) with add_compile_options(/bigobj)

Source/AliveLibAE/Renderer/SoftwareRenderer.cpp
Check `if (mBackBufferTexture)` before `SDL_DestroyTexture`
I was receiving a popup window about a SDL assertion.
=> Renderer assertion on startup

Source/AliveLibAE/FlyingSlig.cpp
Fixes a small typo introduced in commit d599d55b07103460af6b06dc8d2b97edd4f44967, that would cause the Flying Slig in Tunnel 2 of the Mines to never return after the chase sequence making the 4 Mudokon secret (screen MIP2C12) inaccessible.
=> Fix typo in FlyingSlig::sub_4374A0

Source/AliveLibAE/CMakeLists.txt, Source/AliveLibAO/CMakeLists.txt
Clang doesn't seem to implicitly link to `imm32`.
=> Add support for MinGW (MSYS2) Clang builds

README.md
I think it's nicer as you can pick your desired build environment without having to go through all of them
=> Collapse build instructions in README

Source/AliveLibAE/PauseMenu.cpp
Hey, first pr!
Just testing the waters.
This fixes compilation for me on MSVC 2019, Visual studio just _refuses_ to take any signed char pointers for common string types.
By the way, how do you guys normally enable developer_mode?
I had to force it "ON" in options.cmake because it would override the header file at build time but then it shows in git status.
=> Fixed wrong char type in debug code.

Source/AliveLibAE/SwitchStates.cpp
id's in the new qt editor should probably be capped to 256 as well since everything above it screws up things
=> display a warning when a switch id exceeds the max array size

Source/AliveLibAE/BaseGameObject.cpp, Source/AliveLibAE/ObjectIds.cpp, Source/AliveLibAE/ObjectIds.hpp
Fixes #1223  AE OG Bug - The game sometimes gets the wrong type id when quicksaving/quickloading by ensuring that entity ids are unique.
=> Ensure ids are always unique to fix #1223

Source/AliveLibAE/BirdPortal.cpp, Source/AliveLibAO/BirdPortal.cpp
apparently the AE game ender bird portal doesn't have a bird portal exit
=> Use log warning instead of `ALIVE_FATAL` in `vExitPortal`

Source/AliveLibCommon/AnimResources.cpp
it appears that the animid frametableoffsets were swapped so abe got killed too early because the wrong sprite had a bigger rect
=> fix falling item killing abe when it shouldn't

Source/AliveLibAO/Animation.cpp, Source/AliveLibAO/BaseAnimatedWithPhysicsGameObject.cpp, Source/AliveLibAO/ChimeLock.cpp, Source/AliveLibAO/Dove.cpp, Source/AliveLibAO/Elum.cpp
- fix bells leaking when abe dies in a screen with bells
- add some logging when animation init fails
- hack load dove resources (for some reason it can fail during the game ender when you die and pull the lever)
- replace comma with semicolon in Elum.cpp (typo go brr)
=> a couple fixes

appveyor.yml
hopefully resolves crazy audio stuttering for appveyor builds. this seems to mainly happen on appveyor builds and it appears to be fine on azure builds. the only difference i could spot is that appveyor was using `Visual Studio 15 2017` while azure is using a slightly more up to date version `Visual Studio 16 2019`.
=> bump appveyor image to Visual Studio 2022

3rdParty/CMakeLists.txt, Source/Tools/relive_api/CMakeLists.txt, Source/relive_lib/CMakeLists.txt
Using:
Windows 10 64bit
VisualStudio 2022
cmake 3.29.6
The cmake build was failing with error
`Error: CMake file API parsing response files failed. Check for invalid paths in your CMakeLists.txt files. Parsing failed when attempting to parse this path: "C:\\Users\\[...]\\alive_reversing\\3rdParty\\$<BUILD_INTERFACE:"`
I put each line in quotes and put `$<BUILD_INTERFACE` in front of each line, it seems to be working ok now. 
I had also seen it generating some paths with new line characters, like `\\path1\n    \\path2`
Not sure if this would have negative impacts on other platforms.
=> Windows 10 cmake build issues

Source/relive_lib/Renderer/OpenGL3/OpenGLRenderer.cpp
Per title - solution is to move the stats/batcher reset above the early return in `StartFrame`.
=> Fix for memory exhaustion in GL renderer when minimised

CMakeLists.txt, options.cmake
Version requirement bump so that CMake >= 4.0 is happy again.
=> Fixes #1667: bump cmake version requirement to 3.10
