AliveTeam/alive_reversing

Source/AliveLib/Slig.cpp, Source/AliveLib/Slig.hpp
First PR ! Yay (hope it works)
=> Slig motions 31 & 44

Source/AliveLib/Slig.cpp, Source/AliveLib/Slig.hpp
Slig's motions are now 100% complete.
=> Completed Slig's motions

Source/AliveLib/NakedSlig.cpp, Source/AliveLib/NakedSlig.hpp
-Completed Unknown NakedSlig motions.
-Edited some due inappropriate name.
-Edited all to follow the `M_Name_##` pattern
=> impl NakedSlig motions

Source/AliveLib/Fleech.cpp, Source/AliveLib/Fleech.hpp, Source/AliveLib/FlyingSlig.cpp, Source/AliveLib/FlyingSlig.hpp, Source/AliveLib/NakedSlig.cpp, Source/AliveLib/Paramite.cpp, Source/AliveLib/Paramite.hpp, Source/AliveLib/Scrab.cpp, Source/AliveLib/Scrab.hpp, Source/AliveLib/Slig.cpp, Source/AliveLib/Slig.hpp, Source/AliveLib/Slog.cpp, Source/AliveLib/Slog.hpp
impl Fleech AI names
impl FlyingSlig AI names
impl Paramite AI names
impl Scrab AI names
impl Slog AI names
renamed some Slig AI names
=> Big AI names update

Source/AliveLib/Abe.cpp
=> Fix #109 and another bug related to throw action

Source/AliveLib/Scrab.cpp, Source/AliveLib/Scrab.hpp
impl Scrab::M_WalkToFall_14_4A9460
impl Scrab::M_RunToFall_15_4A9430
impl Scrab::M_WalkToRun_16_4A8D60
impl Scrab::M_RunToWalk_17_4A8D90
impl Scrab::M_GetEaten_19_4AA3E0
=> My first functions !

Source/AliveLib/Scrab.cpp
impl Scrab::M_DeathEnd_24_4AA140
impl Scrab::M_FeedToGulp_33_4A9FA0
impl Scrab::M_StandToFeed_35_4AA010
impl Scrab::M_Feed_36_4AA030
impl Scrab::M_LegKick_38_4AA120
impl Scrab::M_DeathBegin_39_4AA190
=> Some other easy Scrab functions

Source/AliveLib/EvilFart.cpp
=> Fart colour fix.

Scripts/Hex2Bits.py
=> Cleaned up/fixed Hex2Bits.py.

Source/AliveLib/GameSpeak.hpp, Source/AliveLib/Glukkon.cpp, Source/AliveLib/Glukkon.hpp, Source/AliveLib/GlukkonSwitch.cpp, Source/AliveLib/MainMenu.cpp
=> Glukkon::PlaySound_4447D0

Source/AliveLib/Glukkon.cpp
=> IsLineOfSightBetween_4403B0 reversed.

Source/AliveLib/Scrab.cpp, Source/AliveLib/Scrab.hpp
Probably a lot of things are done badly or totally wrong. Would need a code review sorry ^^'
=> impl Scrab::AI_ChasingEnemy_1_4A6470

Source/AliveLib/Mudokon.cpp, Source/AliveLib/Mudokon.hpp, Source/AliveLib/Paramite.cpp, Source/AliveLib/Scrab.cpp, Source/AliveLib/Slig.cpp
impl Paramite states enums (100%)
impl Slig states enums (missing 3)
impl Mudokon states enums (100%) + AI names correction
impl more Scrab states names (missing 6)
fix two bugs on Scrab::AI_ChasingEnemy_1_46470
I'm counting on @mouzedrift to find the missing states names 💯
=> Several states enums + bug fixes

Source/AliveLib/Bone.cpp, Source/AliveLib/Bone.hpp
Renamed variables in Bone and BoneBag classes to describe what they do. Also cleaned up logic around field_120 that was not needed.
=> Renamed variables in Bone and BoneBag Classes

Source/AliveLib/Abe.cpp, Source/AliveLib/Abe.hpp, Source/AliveLib/Mudokon.cpp, Source/AliveLib/PauseMenu.cpp
24 and 60 are still to be determined, but both seem to be unused?
=> impl missing Abe States names

Source/AliveLib/Fleech.cpp, Source/AliveLib/NakedSlig.cpp, Source/AliveLib/Slig.cpp, Source/AliveLib/Slog.cpp, Source/AliveLib/SnoozeParticle.cpp, Source/AliveLib/SnoozeParticle.hpp
=> SnoozeParticle Update & Render functions reversed.

Source/AliveLib/Slog.cpp, Source/AliveLib/Slog.hpp
=> Slog::Sfx_4C7D30

Source/AliveLib/Scrab.cpp, Source/AliveLib/Scrab.hpp
=> Sound_4AADB0

Source/AliveLib/Fleech.cpp, Source/AliveLib/Fleech.hpp
=> Fleech Sfx function reversed.

Source/AliveLib/Math.cpp
No guarantees that the current version is 1:1 with OG 😔
=> Math_496F70()

Source/AliveLib/Fleech.cpp, Source/AliveLib/Fleech.hpp, Source/AliveLib/FlyingSlig.cpp, Source/AliveLib/Math.cpp, Source/AliveLib/Math.hpp
=> FleechRender

Source/AliveLib/MainMenu.cpp, Source/AliveLib/MainMenu.hpp
t_Render_Slig_Speak_4D2370()
t_Render_Glukkon_Speak_4D23C0()
t_Render_Scrab_Speak_4D2410()
=> Slig Glukkon Scrab gamespeak numbers.

Source/AliveLib/MainMenu.cpp, Source/AliveLib/MainMenu.hpp
t_Render_ControlerMenu_Text_4D26C0()
t_Render_AbesMotions_Text_4D25E0()
tLoadGame_Render_4D44D0()
OptionsMenuBtnListener_4D1AB0()
=> Main Menu Render Text funcs

Source/AliveLib/Fleech.cpp
=> Fleech fix

Source/AliveLib/Slog.cpp
=> HandleEnemyStopper_4C5340()

Source/AliveLib/Rock.cpp
=> RockSack missing line.

Source/AliveLib/Slig.cpp
=> Slig beat fix.

Source/AliveLib/DemoPlayback.cpp, Source/AliveLib/FlyingSlig.cpp, Source/AliveLib/Mudokon.cpp, Source/AliveLib/Psx.cpp, Source/AliveLib/Scrab.cpp, Source/AliveLib/Well.cpp, Source/AliveLib/Well.hpp
=> Demo playback

Source/AliveLib/InvisibleEffect.cpp, Source/AliveLib/PsxRender.cpp
The Github bug tickets are also invisible 👀
=> Abe invisible bugs fixes.

Source/AliveLib/Abe.cpp, Source/AliveLib/BirdPortal.cpp, Source/AliveLib/Fleech.cpp, Source/AliveLib/Fleech.hpp, Source/AliveLib/Glukkon.cpp, Source/AliveLib/Mudokon.cpp, Source/AliveLib/NakedSlig.cpp, Source/AliveLib/Scrab.cpp, Source/AliveLib/Sound/Sound.cpp
=> More(final?) clang fixes

Source/AliveLib/Abe.cpp, Source/AliveLib/BaseAliveGameObject.cpp, Source/AliveLib/BaseAliveGameObject.hpp, Source/AliveLib/Collisions.cpp, Source/AliveLib/Collisions.hpp, Source/AliveLib/FlyingSlig.cpp, Source/AliveLib/Glukkon.cpp, Source/AliveLib/Leaf.cpp, Source/AliveLib/MineCar.cpp, Source/AliveLib/MineCar.hpp, Source/AliveLib/Mudokon.cpp, Source/AliveLib/NakedSlig.cpp, Source/AliveLib/Paramite.cpp, Source/AliveLib/Scrab.cpp, Source/AliveLib/StatusLight.cpp
Refactor of the State_1() of Minecar's update function.
There's a bug while holding the movement key and going round the corners, the minecar doesn't turn in every angle scenario
=> Minecar State1 refactor

Source/AliveLib/DebugHelpers.cpp, Source/AliveLib/Game.cpp, Source/AliveLib/Input.cpp, Source/AliveLib/Input.hpp, Source/AliveLib/PauseMenu.cpp, Source/AliveLib/Sys.cpp, Source/AliveLib/stdafx.h
=> Function keys now disabled while saving input. Annoying logs disabled.

Source/AliveLibAE/Abe.cpp, Source/AliveLibAE/BaseAliveGameObject.cpp, Source/AliveLibAE/BaseAliveGameObject.hpp, Source/AliveLibAE/Fleech.cpp, Source/AliveLibAE/Mine.cpp, Source/AliveLibAE/Mine.hpp, Source/AliveLibAE/MineCar.cpp, Source/AliveLibAE/MineCar.hpp, Source/AliveLibAE/MotionDetector.hpp, Source/AliveLibAE/Movie.cpp, Source/AliveLibAE/Movie.hpp, Source/AliveLibAE/MovingBomb.cpp, Source/AliveLibAE/MovingBomb.hpp, Source/AliveLibAE/Mudokon.cpp, Source/AliveLibAE/Mudokon.hpp, Source/AliveLibAE/Paramite.cpp, Source/AliveLibAE/Paramite.hpp, Source/AliveLibAE/Scrab.cpp, Source/AliveLibAE/Slig.cpp
I've named a multitude of fields, flags, states and functions across the following classes: Abe, BaseGameAliveObject, Fleech, Mine, MineCar, MotionDetector, Movie, MovingBomb, Mudokon, Paramite, Scrab and Slig.
=> Named a Multitude of Fields, Flags, States and Functions Across Various Classes

README.md, Source/AliveDllAE/CMakeLists.txt, Source/AliveDllAO/CMakeLists.txt
=> Output paths as env variables

Source/AliveLibAE/Abe.cpp, Source/AliveLibAE/DebugHelpers.cpp, Source/AliveLibAE/Factory.cpp, Source/AliveLibAE/Game.cpp, Source/AliveLibAE/Game.hpp, Source/AliveLibAE/MainMenu.cpp, Source/AliveLibAE/Map.cpp, Source/AliveLibAE/Movie.cpp, Source/AliveLibAO/Abe.cpp, Source/AliveLibAO/Abe.hpp, Source/AliveLibAO/CMakeLists.txt, Source/AliveLibAO/Factory.cpp, Source/AliveLibAO/Game.hpp, Source/AliveLibAO/PauseMenu.cpp, Source/AliveLibAO/PauseMenu.hpp
=> Factory_AbeStart_486050

Source/AliveLibAO/Abe.cpp, Source/AliveLibAO/Abe.hpp, Source/AliveLibAO/Animation.hpp, Source/AliveLibAO/BaseAliveGameObject.hpp, Source/AliveLibAO/BaseAnimatedWithPhysicsGameObject.cpp, Source/AliveLibAO/BaseAnimatedWithPhysicsGameObject.hpp, Source/AliveLibAO/Map.cpp, Source/AliveLibAO/RollingBallStopper.cpp
=> Abe vRender

Source/AliveLibAE/Abe.cpp, Source/AliveLibAE/Abe.hpp, Source/AliveLibAE/PauseMenu.cpp, Source/AliveLibAO/Abe.cpp, Source/AliveLibAO/Abe.hpp, Source/AliveLibAO/BaseAnimatedWithPhysicsGameObject.cpp, Source/AliveLibAO/BaseAnimatedWithPhysicsGameObject.hpp, Source/AliveLibAO/CMakeLists.txt, Source/AliveLibAO/Elum.cpp, Source/AliveLibAO/Elum.hpp, Source/AliveLibAO/Factory.cpp, Source/AliveLibAO/Map.cpp, Source/AliveLibAO/ResourceManager.cpp, Source/AliveLibAO/ResourceManager.hpp, Source/AliveLibAO/ThrowableArray.cpp, Source/AliveLibAO/ThrowableArray.hpp
Abe::vScreenChanged_422640
Factory_ElumStart_Unknown_4873D0
=> Abe::vScreenChanged_422640() (and friends)

Source/AliveLibAO/Elum.cpp, Source/AliveLibAO/Elum.hpp
=> Elum::Spawn_410E90()

Source/AliveLibAO/Elum.cpp, Source/AliveLibAO/Elum.hpp
=> Elum stuff

README.md, Scripts/IDA_SyncDecompiledFuncs.py, Source/AliveDllAO/CMakeLists.txt
=> Path consistency fix.

Source/AliveLibAE/BulletShell.hpp, Source/AliveLibAE/Grenade.cpp, Source/AliveLibAE/Grenade.hpp, Source/AliveLibAE/ResourceManager.hpp, Source/AliveLibAE/TrapDoor.cpp, Source/AliveLibAE/TrapDoor.hpp
Files affected:
* BulletShell.hpp
* Grenade.cpp
* Grenade.hpp
* ResourceManager.hpp
* TrapDoor.cpp
* TrapDoor.hpp
=> Fixed unnamed fields

Source/AliveLibAE/Abe.cpp, Source/AliveLibAE/FlyingSlig.cpp, Source/AliveLibAE/Mudokon.cpp, Source/AliveLibAE/Slig.cpp, Source/AliveLibAE/Switch.cpp, Source/AliveLibAE/Switch.hpp, Source/AliveLibAO/BaseGameObject.hpp, Source/AliveLibAO/CMakeLists.txt, Source/AliveLibAO/Factory.cpp, Source/AliveLibAO/FallingItem.cpp, Source/AliveLibAO/Sfx.cpp, Source/AliveLibAO/Sfx.hpp, Source/AliveLibAO/Switch.cpp, Source/AliveLibAO/Switch.hpp
=> fix bugs & impl switch

Source/AliveLibAE/Bullet.cpp, Source/AliveLibAE/Bullet.hpp, Source/AliveLibAE/DeathGas.cpp, Source/AliveLibAE/DeathGas.hpp, Source/AliveLibAE/DoorFlame.hpp, Source/AliveLibAE/Electrocute.hpp, Source/AliveLibAE/Explosion.cpp, Source/AliveLibAE/Explosion.hpp, Source/AliveLibAE/FG1.cpp, Source/AliveLibAE/FG1.hpp, Source/AliveLibAE/FartMachine.hpp, Source/AliveLibAE/GameSpeak.hpp, Source/AliveLibAE/LCDScreen.hpp, Source/AliveLibAE/Path.hpp, Source/AliveLibAE/Rock.cpp, Source/AliveLibAE/Rock.hpp, Source/AliveLibAE/ScreenShake.hpp, Source/AliveLibAE/SecurityDoor.cpp, Source/AliveLibAE/SecurityDoor.hpp, Source/AliveLibAE/SlapLock.hpp, Source/AliveLibAE/Switch.hpp, Source/AliveLibAE/UXB.hpp, Source/AliveLibAE/WorkWheel.hpp
Affected files:
* Bullet.cpp
* Bullet.hpp
* DeathGas.cpp
* DeathGas.hpp
* DoorFlame.hpp
* Electrocute.hpp
* Explosion.cpp
* Explosion.hpp
* FG1.cpp
* FG1.hpp
* FartMachine.hpp
* GameSpeak.hpp
* LCDScreen.hpp
* Path.hpp
* Rock.cpp
* Rock.hpp
* ScreenShake.hpp
* SecurityDoor.cpp
* SecurityDoor.hpp
* SlapLock.hpp
* Switch.hpp
* UXB.hpp
* WorkWheel.hpp
=> Fixed more unnamed fields.

Source/AliveLibAE/Abe.cpp, Source/AliveLibAE/Abe.hpp, Source/AliveLibAE/FlyingSlig.cpp, Source/AliveLibAE/MineCar.cpp, Source/AliveLibAE/MotionDetector.cpp, Source/AliveLibAE/Mudokon.cpp, Source/AliveLibAE/Mudokon.hpp, Source/AliveLibAE/PauseMenu.cpp, Source/AliveLibAO/Abe.cpp, Source/AliveLibAO/Abe.hpp
Done while working on AO Mud motions
=> Naming consistency

Source/AliveLibAO/OrbWhirlWind.cpp
=> fix orb crash

Source/AliveLibAO/Abe.cpp
=> fix abe can't possess the chime lock ball

Source/AliveLibAE/CameraSwapper.cpp, Source/AliveLibAE/GameSpeak.cpp, Source/AliveLibAE/GameSpeak.hpp, Source/AliveLibAE/RockSack.hpp, Source/AliveLibAE/Scrab.cpp, Source/AliveLibAE/Scrab.hpp, Source/AliveLibAE/ScrabSpawner.hpp, Source/AliveLibAE/ScreenManager.hpp, Source/AliveLibAE/SecurityDoor.cpp, Source/AliveLibAE/SecurityDoor.hpp
Named fields, states and functions in the Camera, GameSpeak, Scrab, ScrabSpawner, ScreenManager and SecurityDoor classes. Added missing #pragma once command into RockSack.hpp.
=> Named Fields, States and Functions in Various Classes

Source/AliveLibAE/Abe.cpp
https://www.youtube.com/watch?v=hHioSCNnAps
=> fix OG bug where abe doesn't transform into shrykull when you use gamespeak and then immediately chant

Source/AliveLibAE/BaseAliveGameObject.cpp, Source/AliveLibAE/BirdPortal.cpp, Source/AliveLibAE/BoomMachine.cpp, Source/AliveLibAE/Glukkon.cpp, Source/AliveLibAE/Grenade.hpp, Source/AliveLibAE/LiftPoint.cpp, Source/AliveLibAE/Map.cpp, Source/AliveLibAE/Mudokon.cpp, Source/AliveLibAE/Paramite.cpp, Source/AliveLibAE/PauseMenu.cpp, Source/AliveLibAE/Spark.cpp, Source/AliveLibAO/BirdPortal.cpp, Source/AliveLibAO/Elum.cpp, Source/AliveLibAO/Mudokon.hpp, Source/AliveLibAO/Rock.cpp, Source/AliveLibAO/Slig.cpp, Source/AliveLibAO/Slig.hpp, Source/AliveLibAO/Slog.hpp, Source/AliveLibAO/WinMain.cpp
~~i'm not sure which data type i should use for: `int Slig::Speak_467700(unsigned __int16 /*a2*/)`
IDA output is: `eSligStates __thiscall Slig::Speak_467700(Slig *this, unsigned __int16 a2)`~~
=> Impl some states

Source/AliveLibAO/Paramite.cpp, Source/AliveLibAO/Paramite.hpp
There might be some things to check, I've tried my best to sort out if/else statements
=> Paramite brains + Brain_Death_448BF0

Source/AliveLibAO/Abe.cpp, Source/AliveLibAO/Abe.hpp
=> State_30_HopMid_4264D0()

Source/AliveLibAE/ParamiteWeb.cpp, Source/AliveLibAO/Animation.cpp, Source/AliveLibAO/Animation.hpp, Source/AliveLibAO/ParamiteWeb.cpp, Source/AliveLibAO/ParamiteWeb.hpp, Source/AliveLibAO/Rope.cpp, Source/AliveLibAO/Rope.hpp, Source/AliveLibAO/ShadowZone.cpp, Source/AliveLibAO/ShadowZone.hpp
=> ParamiteWeb::VRender_48AB10()

Source/AliveLibAE/Abe.cpp, Source/AliveLibAE/Animation.cpp, Source/AliveLibAE/DemoPlayback.cpp, Source/AliveLibAE/Fleech.cpp, Source/AliveLibAE/FlyingSlig.cpp, Source/AliveLibAE/Glukkon.cpp, Source/AliveLibAE/MainMenu.cpp, Source/AliveLibAE/Map.cpp, Source/AliveLibAE/MusicController.cpp, Source/AliveLibAE/MusicController.hpp, Source/AliveLibAE/MusicTrigger.cpp, Source/AliveLibAE/NakedSlig.cpp, Source/AliveLibAE/Paramite.cpp, Source/AliveLibAE/ResourceManager.hpp, Source/AliveLibAE/Scrab.cpp, Source/AliveLibAE/Slig.cpp, Source/AliveLibAE/SligGetPantsAndWings.cpp, Source/AliveLibAE/SligGetPantsAndWings.hpp, Source/AliveLibAE/SligSpawner.hpp, Source/AliveLibAE/Slog.cpp, Source/AliveLibAE/Slog.hpp
Named fields, flags, functions, states and local variables in the `MusicController`, `ResourceManager`, `SligGetPantsAndWings` and `Slog` classes.
=> Named Fields, Flags, Functions, States and Local Variables in the Slog Class and Other Classes

Source/AliveLibAO/TimedMine.cpp, Source/AliveLibAO/TimedMine.hpp
=> A few timed mines functions

Source/AliveLibAE/Abe.cpp, Source/AliveLibAO/Abe.cpp, Source/AliveLibAO/Abe.hpp, Source/AliveLibAO/Door.cpp, Source/AliveLibAO/Door.hpp
=> More stuff

Source/AliveLibAE/BaseGameObject.hpp, Source/AliveLibAE/Bone.cpp, Source/AliveLibAE/DebugHelpers.cpp, Source/AliveLibAE/MainMenu.cpp, Source/AliveLibAE/Map.cpp, Source/AliveLibAE/Movie.cpp, Source/AliveLibAE/ResourceManager.hpp, Source/AliveLibAE/Teleporter.cpp, Source/AliveLibAE/Teleporter.hpp, Source/AliveLibAE/Text.cpp, Source/AliveLibAE/Text.hpp, Source/AliveLibAE/Throwable.cpp, Source/AliveLibAE/Throwable.hpp, Source/AliveLibAE/ThrowableArray.cpp, Source/AliveLibAE/ThrowableArray.hpp, Source/AliveLibAE/ThrowableTotalIndicator.cpp, Source/AliveLibAE/ThrowableTotalIndicator.hpp, Source/AliveLibAE/TimedMine.cpp, Source/AliveLibAE/TimedMine.hpp, Source/AliveLibAE/TimerTrigger.hpp
Named fields, flags and states in the `BaseGameObject`, `Bone`, `ResourceManager`, `Teleporter`, `Text`, `Throwable`, `ThrowableArray`, `ThrowableTotalIndicator` and `TimedMine` classes.
=> Named Fields, Flags and States in Various Classes

Source/AliveLibAE/TorturedMudokon.cpp, Source/AliveLibAE/TorturedMudokon.hpp, Source/AliveLibCommon/AnimResources.hpp
Named fields, functions and states and refactored a decompiled if/else condition into a switch/case condition in the `TorturedMudokon` class.
=> [AE] Naming and Refactoring for the TorturedMudokon Class

Source/AliveLibAE/Abe.cpp, Source/AliveLibAO/Abe.cpp, Source/AliveLibAO/Alarm.cpp, Source/AliveLibAO/CMakeLists.txt, Source/AliveLibAO/Events.hpp, Source/AliveLibAO/MusicTrigger.cpp, Source/AliveLibAO/SaveGame.cpp, Source/AliveLibAO/SaveGame.hpp
=> Abe::State_60_Dead_42C4C0 & Abe::State_61_Respawn_42CD20

Source/AliveLibAO/Abe.cpp, Source/AliveLibAO/BackgroundMusic.cpp, Source/AliveLibAO/BaseBomb.cpp, Source/AliveLibAO/Bat.cpp, Source/AliveLibAO/BellHammer.cpp, Source/AliveLibAO/Door.cpp, Source/AliveLibAO/DoorLight.cpp, Source/AliveLibAO/Dove.cpp, Source/AliveLibAO/Elum.cpp, Source/AliveLibAO/Explosion.cpp, Source/AliveLibAO/FallingItem.cpp, Source/AliveLibAO/Midi.cpp, Source/AliveLibAO/Midi.hpp, Source/AliveLibAO/Mudokon.cpp, Source/AliveLibAO/Paramite.cpp, Source/AliveLibAO/RollingBall.cpp, Source/AliveLibAO/ScopedSeq.cpp, Source/AliveLibAO/SecurityDoor.cpp, Source/AliveLibAO/SecurityDoor.hpp, Source/AliveLibAO/Slig.cpp, Source/AliveLibAO/Slog.cpp
i didn't add the states enum yet because it looks a bit different compared to AE and i'm not really in the mood RN after VS intellisense decided to not work whatsoever.
=> impl SecurityDoor::VUpdate_461AD0

Source/AliveLibAE/TrapDoor.cpp, Source/AliveLibAE/TrapDoor.hpp, Source/AliveLibAE/UXB.cpp, Source/AliveLibAE/UXB.hpp, Source/AliveLibAE/VRam.cpp, Source/AliveLibAE/VRam.hpp, Source/AliveLibAE/Water.cpp, Source/AliveLibAE/Water.hpp, Source/AliveLibAE/Well.cpp, Source/AliveLibAE/Well.hpp, Source/AliveLibAE/WheelSyncer.cpp, Source/AliveLibAE/WheelSyncer.hpp, Source/AliveLibAE/WorkWheel.cpp, Source/AliveLibAE/WorkWheel.hpp
Named fields and states and converted integers to enumerations in the `TrapDoor`, `UXB`, `VRam`, `Well`, `Water`, `WheelSyncer` and `WorkWheel` classes.
=> Named Variables in the TrapDoor, UXB, VRam, Well, Water, WheelSyncer and WorkWheel Classes

Source/AliveLibAE/Scrab.cpp
previously scrabs would just idle forever once they are supposed to chase an enemy
=> scrab bug fix

Source/AliveLibAE/Abe.cpp, Source/AliveLibAO/Abe.cpp, Source/AliveLibAO/Abe.hpp, Source/AliveLibAO/Events.hpp, Source/AliveLibAO/Mudokon.cpp
=> Abe::State_77_WellBegin_430F10()

Source/AliveLibAE/Greeter.cpp, Source/AliveLibAE/SecurityOrb.cpp, Source/AliveLibAE/Shrykull.cpp, Source/AliveLibAE/ZapLine.cpp, Source/AliveLibAE/ZapLine.hpp
Named fields, functions and states in the `ZapLine` class. Converted the `ZapLine` types from integers into enumerations.
=> Named Fields, Functions and States in the ZapLine Class

Source/AliveLibAE/Abe.cpp, Source/AliveLibAE/CameraSwapper.cpp, Source/AliveLibAE/Game.cpp, Source/AliveLibAE/Glukkon.cpp, Source/AliveLibAE/MainMenu.cpp, Source/AliveLibAE/Map.cpp, Source/AliveLibAE/ScreenManager.cpp, Source/AliveLibAE/ScreenManager.hpp, Source/AliveLibAO/Abe.cpp, Source/AliveLibAO/Abe.hpp, Source/AliveLibAO/BellSong.cpp, Source/AliveLibAO/BellSong.hpp, Source/AliveLibAO/CMakeLists.txt, Source/AliveLibAO/CameraSwapper.cpp, Source/AliveLibAO/DemoPlayback.cpp, Source/AliveLibAO/DemoPlayback.hpp, Source/AliveLibAO/Map.cpp, Source/AliveLibAO/PathData.hpp, Source/AliveLibAO/ResourceManager.hpp, Source/AliveLibAO/SaveGame.cpp, Source/AliveLibAO/SaveGame.hpp, Source/AliveLibAO/ScreenManager.cpp, Source/AliveLibAO/ScreenManager.hpp
=> Abe::State_88_HandstoneBegin_430590()

Source/AliveLibAO/Abe.cpp, Source/AliveLibAO/Abe.hpp
=> Abe::State_150_Chant_42FD50()

Source/AliveLibAE/Io.cpp, Source/AliveLibAE/Io.hpp, Source/AliveLibAO/Collisions.cpp, Source/AliveLibAO/MainMenu.cpp, Source/AliveLibAO/MainMenu.hpp, Source/AliveLibAO/stdafx_ao.h
impl Menu::StringsEqual_47DA20
=> impl Menu::To_Load_Update_47D8E0

Source/AliveLibAE/Abe.cpp, Source/AliveLibAE/Abe.hpp, Source/AliveLibAE/BaseGameObject.hpp, Source/AliveLibAE/BirdPortal.cpp, Source/AliveLibAE/DDCheat.cpp, Source/AliveLibAE/DebugHelpers.cpp, Source/AliveLibAE/Fleech.cpp, Source/AliveLibAE/Mudokon.cpp, Source/AliveLibAE/Mudokon.hpp, Source/AliveLibAE/MusicController.cpp, Source/AliveLibAE/MusicController.hpp, Source/AliveLibAE/PauseMenu.cpp, Source/AliveLibAE/QuikSave.cpp, Source/AliveLibAE/Shrykull.cpp, Source/AliveLibAE/SlapLock.cpp, Source/AliveLibAE/Slig.cpp, Source/AliveLibAE/Slig.hpp
Named fields, flags, structures and functions in the `Abe` class. Also named an object type in the `BaseGameObject` class and a couple of fields in the `MusicController` class.
=> [AE] Named Almost Everything in the Abe Class

Source/AliveLibAE/DebugHelpers.cpp, Source/AliveLibAO/Mudokon.cpp
=> fix #847 + float cast fix

Source/AliveLibAO/MainMenu.cpp, Source/AliveLibAO/MainMenu.hpp, Source/AliveLibAO/SaveGame.cpp, Source/AliveLibAO/SaveGame.hpp
Standalone can boot a demo that does nothing now
=> MainMenuTransition / SaveGame::Load / KillObjects

Source/AliveLibAE/Input.cpp, Source/AliveLibAE/Input.hpp, Source/AliveLibAO/Input.cpp
barely works but can start a game etc
=> AO standalone input hack

Source/AliveLibAO/Psx.cpp
Fix Abe's Oddysee standalone not running on GNU + Linux systems,
=> Fix Abe's Oddysee Standalone Not Running on GNU + Linux Systems

Source/AliveLibAE/MainMenu.cpp, Source/AliveLibAE/MainMenu.hpp
Some Update function return values are still in int format (0xFFFF0002, etc.).
As we've discussed, those will be converted to a struct, but that will have to be in another PR as this one has already gotten too big
=> [AE] MainMenu class refactoring, MainMenuCams enum

Source/AliveLibAE/DebugHelpers.cpp, Source/AliveLibAE/MainMenu.cpp, Source/AliveLibAE/MainMenu.hpp
Still a lot of renaming and organizing to be done, but stopping here for now to keep the PR at a reasonable size.
=> [AE] MainMenu refactoring, part II

Source/AliveLibAE/Animation.cpp, Source/AliveLibAE/Animation.hpp, Source/AliveLibAE/AnimationBase.cpp, Source/AliveLibAE/AnimationBase.hpp, Source/AliveLibAE/AnimationUnknown.cpp, Source/AliveLibAE/AnimationUnknown.hpp, Source/AliveLibAE/BaseAnimatedWithPhysicsGameObject.hpp, Source/AliveLibAE/CMakeLists.txt
Separated `AnimationBase` and `AnimationUnknown` classes out into their own separate set of files.
=> Separated `AnimationBase` and `AnimationUnknown` Classes into Separate Files

Source/AliveLibAO/Map.cpp
found by samlaptop when attempting a speed run, somehow the play sound func makes the slig shoot earlier
=> fix slig shoots abe on elum when he shouldnt

Source/AliveLibAO/FootSwitch.hpp, Source/AliveLibAO/Paramite.cpp, Source/AliveLibAO/RollingBall.cpp, Source/AliveLibAO/RollingBall.hpp
found by sam and can be seen here: https://clips.twitch.tv/BlazingSpunkyNewtVoHiYo
but there is another bug i still need to fix to make the strat work
=> fix scuffed paramite meat finding, fix broken foot switch and fix rolling ball not rolling fast enough

CMakeLists.txt, appveyor.yml, assets/CMakeLists.txt, azure-pipelines.yml
To generate a package:
```
cd [relive_dir]
mkdir build
cd build
cmake -S .. -B .
make
cpack -G DEB
```
`DEB` being capitalized is important.
=> Fixed and enabled CPack .deb generation

Source/AliveLibAE/Abe.cpp, Source/AliveLibAE/Abe.hpp, Source/AliveLibAE/Bullet.cpp, Source/AliveLibAE/Bullet.hpp, Source/AliveLibAE/Glukkon.cpp, Source/AliveLibAE/Greeter.cpp, Source/AliveLibAE/Movie.cpp, Source/AliveLibAE/Movie.hpp, Source/AliveLibAE/Mudokon.cpp, Source/AliveLibAE/Slig.cpp, Source/AliveLibAE/Slog.cpp
- Named local variables in the `Abe` class.
- Named fields in the `Bullet` and `Movie` classes.
- Fixed spelling and grammar mistakes in variables and comments.
=> [AE] Named variables in the Abe, Bullet and Movie classes. Fixed spelling and grammar mistakes.

Source/AliveLibAO/PathData.hpp, Source/Tools/alive_api/AOTlvs.hpp, Source/Tools/alive_api/ByteStream.hpp, Source/Tools/alive_api/ITypeBase.hpp, Source/Tools/alive_api/JsonDocument.cpp, Source/Tools/alive_api/JsonDocument.hpp, Source/Tools/alive_api/TlvObjectBase.hpp, Source/Tools/alive_api/TypesCollection.cpp, Source/Tools/alive_api/TypesCollection.hpp, Source/Tools/alive_api/alive_api.cpp, Source/Tools/alive_api/alive_api_test.cpp
-Can be written out for BA path 16 but most objects not yet added
-AO json read/write of R1 path 19 producing matching lvl 🥳
=> editor api - AE json writing wip

Source/AliveLibAE/BirdPortal.cpp, Source/AliveLibAE/BirdPortal.hpp, Source/AliveLibAE/BoomMachine.cpp, Source/AliveLibAE/BoomMachine.hpp, Source/Tools/alive_api/AETlvs.hpp
Also fix a typo in Path_BirdPortal
=> Change Path_BoomMachine.field_12_nozzle_side type to XDirection_short

Source/AliveLibAE/Fleech.cpp, Source/AliveLibAE/Fleech.hpp
Rename Fleech::field_15A to field_15A_chase_timer
=> Rename Fleech::field_158 to field_158_chase_delay

Source/AliveLibAE/Scrab.cpp, Source/AliveLibAE/Scrab.hpp
https://github.com/AliveTeam/alive_reversing/issues/1018
=> #1018 fix. Scrab chase logic less janky

Source/AliveLibAE/FlyingSlig.cpp, Source/AliveLibAE/FlyingSlig.hpp
Named some fields, flags, functions and arrays in the `FlyingSlig` class.
=> [AE] Named some Fields, Flags, Functions and Arrays in the FlyingSlig Class

3rdParty/CMakeLists.txt
Added closing angle brackets to jsonxx, imgui and glm's BUILD_INTERFACE.
=> Fixed brackets in 3rdParty CMakeLists.txt

Source/AliveLibAE/Animation.cpp, Source/AliveLibAE/Animation.hpp, Source/AliveLibAE/AnimationBase.hpp, Source/AliveLibAE/AnimationUnknown.cpp, Source/AliveLibAE/Electrocute.cpp, Source/AliveLibAE/Font.cpp, Source/AliveLibAE/InvisibleEffect.cpp, Source/AliveLibAE/InvisibleEffect.hpp, Source/AliveLibAE/LCDScreen.cpp, Source/AliveLibAE/Psx.cpp, Source/AliveLibAE/Renderer/DirectX9Renderer.cpp, Source/AliveLibAE/Renderer/DirectX9Renderer.hpp, Source/AliveLibAE/Renderer/IRenderer.cpp, Source/AliveLibAE/Renderer/IRenderer.hpp, Source/AliveLibAE/Renderer/OpenGLRenderer.cpp, Source/AliveLibAE/Renderer/OpenGLRenderer.hpp, Source/AliveLibAE/Renderer/SoftwareRenderer.cpp, Source/AliveLibAE/Renderer/SoftwareRenderer.hpp, Source/AliveLibAE/Shadow.cpp, Source/AliveLibAE/VRam.cpp, Source/AliveLibAE/Water.cpp, Source/AliveLibAO/Animation.cpp, Source/AliveLibAO/Electrocute.cpp, Source/AliveLibAO/Font.cpp, Source/AliveLibAO/LCDScreen.cpp, Source/AliveLibAO/VRam.cpp
AO changes will be added before merging
=> reduce conditional compliation logic for GL rendering

CMakeLists.txt, Source/AliveLibAE/DDraw.cpp, Source/AliveLibAE/DDraw.hpp, Source/AliveLibAE/Game.cpp, Source/AliveLibAE/LvlArchive.cpp, Source/AliveLibAE/Movie.cpp, Source/AliveLibAE/Psx.hpp, Source/AliveLibAE/ResourceManager.hpp, Source/AliveLibAE/Sys.cpp, Source/AliveLibAE/Throwable.hpp, Source/AliveLibAE/VGA.cpp, Source/AliveLibAE/bmp.hpp, Source/AliveLibAO/Game.cpp, Source/AliveLibAO/PathData.hpp, Source/AliveLibAO/Psx.cpp, Source/AliveLibAO/Psx.hpp, Source/AliveLibCommon/AddPointer.hpp, Source/AliveLibCommon/FixedPoint_common.hpp, Source/AliveLibCommon/pch_shared.h, Source/Tools/alive_api/JsonUpgrader.hpp
**Merge after #1239**
```bash
make clean; time make -j8 AliveExeAO AliveExeAE AliveExe
> 37.270 total
```
```bash
make clean; time make -j8 AliveExeAO AliveExeAE AliveExe
> 25.806 total
```
=> Improve PCH performance

Source/AliveLibAO/Abe.cpp
=> Added Fast GameSpeak

Source/AliveLibAE/PauseMenu.cpp, Source/AliveLibAE/Sys.cpp, Source/AliveLibAE/Sys.hpp, Source/AliveLibAO/PauseMenu.cpp
=> Exit save menu using controller

Source/AliveLibAO/MainMenu.cpp
=> Fixes automatic scroll when exiting Load Menu

Source/AliveLibAO/PauseMenu.cpp
=> Pause Menu controls like PS1

Source/AliveLibAO/MainMenu.cpp, Source/AliveLibAO/MainMenu.hpp
=> Prevents users from editing Speak1 and Speak2 on Keyboard

Source/AliveLibAO/Movie.cpp, Source/AliveLibCommon/PSXMDECDecoder.cpp, Source/AliveLibCommon/PSXMDECDecoder.h
#1309 
Dropbox Screenshots: https://www.dropbox.com/sh/lzkj0hxnbeuidkd/AACoSzslWPUzO3BHG1hTKQQla?dl=0
Turn monitor brightness up to view the artifacting (left side of screen)
Fourth image has brightness increased by 4 to try and match the OG, but artifacting still remains...
=> Fix FMV Colors (but not artifacting)

Source/AliveLibAO/PauseMenu.cpp
Fixes at least 1 issue for #1325
=> fix implicit type conversion breaking for arm target

Source/AliveLibAE/Collisions.cpp, Source/AliveLibAE/Collisions.hpp, Source/AliveLibAE/ExplosionSet.cpp, Source/AliveLibAE/ExplosionSet.hpp, Source/AliveLibAE/Fleech.cpp, Source/AliveLibAE/Fleech.hpp, Source/AliveLibAE/Slig.cpp, Source/AliveLibAE/Slig.hpp, Source/Tools/relive_api/JsonReaderBase.hpp, Source/Tools/relive_api/TlvsAE.hpp, Source/Tools/relive_api/TlvsAO.hpp, Source/Tools/relive_api/TypesCollectionAE.cpp, Source/Tools/relive_api/relive_api.cpp
those fields with no references are really a huge pain :AnnoyingSlurg:
=> more AE documentation for the editor

Source/AliveLibAE/CrawlingSligButton.cpp, Source/AliveLibAE/CrawlingSligButton.hpp, Source/AliveLibAE/Fleech.cpp, Source/AliveLibAE/Fleech.hpp, Source/AliveLibAE/FlyingSlig.cpp, Source/AliveLibAE/FlyingSligSpawner.hpp, Source/AliveLibAE/Glukkon.cpp, Source/AliveLibAE/Glukkon.hpp, Source/AliveLibAE/Greeter.cpp, Source/AliveLibAE/Greeter.hpp, Source/AliveLibAE/LiftMover.cpp, Source/AliveLibAE/LiftMover.hpp, Source/AliveLibAE/Mudokon.cpp, Source/AliveLibAE/Mudokon.hpp, Source/AliveLibAE/Slig.cpp, Source/AliveLibAE/Slig.hpp, Source/AliveLibAE/SligSpawner.cpp, Source/AliveLibAE/SligSpawner.hpp, Source/Tools/relive_api/TlvsAE.hpp, Source/Tools/relive_api/TypesCollectionAE.cpp
=> AE editor documentation almost done

Source/AliveLibAE/Map.cpp, Source/AliveLibAE/Map.hpp, Source/AliveLibAE/PathData.cpp, Source/AliveLibAE/PathDataExtensions.cpp, Source/AliveLibAO/Map.cpp, Source/AliveLibAO/Map.hpp, Source/AliveLibAO/PathData.cpp, Source/AliveLibAO/PathDataExtensions.cpp
It got a bit screwed from being re-arranged to support custom levels. Also the 30 path limit removed.
=> Fix path handling

Source/AliveLibAE/Input.cpp, Source/AliveLibAE/Psx.cpp, Source/AliveLibAE/Sound/SDLSoundSystem.cpp
but will prob break on weaker pcs
=> add latency_hack option that defaults to true to reduce cpu usage

Source/AliveLibAO/Abe.cpp, Source/AliveLibCommon/AnimResources.cpp, Source/AliveLibCommon/AnimResources.hpp
there are still a couple bans left which i cant figure out rn ⚰️
=> replace some placeholder bans with the actual bans

Source/AliveLibAE/Movie.cpp, Source/AliveLibAE/Movie.hpp
=> AE bugfix: disable reverb in cutscenes (#1126)

Source/AliveLibAE/BirdPortal.cpp, Source/AliveLibAO/BaseAliveGameObject.cpp, Source/AliveLibAO/BirdPortal.cpp
sometimes people forget adding an exit and wonder why the game crashes :gobbins:
=> ALIVE_FATAL when no bird portal exit has been found

Source/Tools/relive_api/TlvsAO.hpp
there are a bunch of objects that still crash the game because of level checks :/
=> Add AO resources to lvl when exporting

Source/AliveLibAO/Input.cpp
https://github.com/AliveTeam/alive_reversing/issues/1480
=> Changed the Enum::eGameSpeak5 and 8

Source/AliveLibAO/Elum.cpp, Source/AliveLibAO/Map.cpp
Fixes #1342 - AO Rev Bug - You can easily get stuck in a movie transition loop at the beginning of scrabania
=> Fix bug #1342 - movie transition loop when riding elum

Source/AliveLibAO/BaseAliveGameObject.cpp
=> add some logging showing how the mystery of start controller direction

Source/AliveLibAE/MainMenu.cpp
=> fix demo autoplay order being off by 1

Source/AliveLibAO/Scrab.cpp
OG bug
this caused some desyncs when running the autoplayer on windows/linux
=> fix out of bounds read in sRunJumpBeginVelTable_4BC8A0

Source/AliveLibAE/BaseAnimatedWithPhysicsGameObject.cpp, Source/AliveLibAE/BaseGameObject.cpp, Source/AliveLibAE/Events.cpp, Source/AliveLibAE/Game.cpp, Source/AliveLibAE/MusicController.cpp, Source/AliveLibAE/ObjectIds.cpp, Source/AliveLibAO/BaseAnimatedWithPhysicsGameObject.cpp, Source/AliveLibAO/BaseBomb.cpp, Source/AliveLibAO/BaseGameObject.cpp, Source/AliveLibAO/Events.cpp, Source/AliveLibCommon/BaseGameAutoPlayer.cpp, Source/AliveLibCommon/BaseGameAutoPlayer.hpp
[but maybe we can fix the AE de-sync?]
=> break all recordings and cause hard merge conflicts

Source/AliveLibAE/BaseAnimatedWithPhysicsGameObject.cpp, Source/AliveLibAE/BaseGameObject.cpp, Source/AliveLibAE/Events.cpp, Source/AliveLibAE/Game.cpp, Source/AliveLibAE/MusicController.cpp, Source/AliveLibAE/ObjectIds.cpp, Source/AliveLibAO/BaseAnimatedWithPhysicsGameObject.cpp, Source/AliveLibAO/BaseBomb.cpp, Source/AliveLibAO/BaseGameObject.cpp, Source/AliveLibAO/Events.cpp, Source/AliveLibCommon/BaseGameAutoPlayer.cpp, Source/AliveLibCommon/BaseGameAutoPlayer.hpp
Reverts AliveTeam/alive_reversing#1540
=> Revert "break all recordings and cause hard merge conflicts"

Source/AliveLibAE/Abe.cpp
=> fix inverted RunToWalk/MidRunToWalk

Source/AliveLibCommon/Sys_common.cpp
=> return default msgbox response on display failure

Source/Tools/relive_api/JsonModelTypes.hpp, Source/Tools/relive_api/relive_api.cpp
fixes https://github.com/AliveTeam/qt-editor/issues/155
=> fix a qt editor crash when exporting s1.lvl

Source/AliveLibAE/Game.cpp, Source/AliveLibAO/Game.cpp
=> fix `latency_hack` not working properly when changing it to false in abe2.ini

Source/AliveLibAE/Abe.cpp, Source/AliveLibAE/Factory.cpp, Source/AliveLibAE/RollingBall.cpp, Source/AliveLibAE/RollingBall.hpp, Source/AliveLibAO/Abe.cpp, Source/AliveLibAO/Factory.cpp, Source/AliveLibAO/RollingBall.cpp, Source/AliveLibAO/RollingBall.hpp, Source/relive_lib/CMakeLists.txt, Source/relive_lib/GameObjects/RollingBallShaker.cpp, Source/relive_lib/GameObjects/RollingBallShaker.hpp, Source/relive_lib/GameObjects/RollingBallStopper.cpp, Source/relive_lib/GameObjects/RollingBallStopper.hpp, Source/relive_lib/Sfx.cpp
The rolling ball sprites don't exist in the released pc version of AE so they need to be copied over from AO
=> Implement `RollingBall` in AE

Source/AliveLibAE/FlyingSlig.cpp, Source/AliveLibAE/FlyingSlig.hpp, Source/Tools/editor/Source/EditorTab.cpp, Source/Tools/editor/Source/ResizeableArrowItem.cpp, Source/Tools/editor/Source/ResizeableArrowItem.hpp
fixes #1625 and https://github.com/AliveTeam/qt-editor/issues/128
=> fix editor context menu sometimes not appearing, fix moving multiple collisions

Source/AliveLibAE/InvisibleEffect.cpp, Source/relive_lib/Animation.cpp, Source/relive_lib/Clamp.hpp, Source/relive_lib/Engine.cpp, Source/relive_lib/Renderer/IRenderer.cpp, Source/relive_lib/Renderer/IRenderer.hpp, Source/relive_lib/Renderer/OpenGL3/OpenGLRenderer.cpp, Source/relive_lib/Renderer/SDL2/Sdl2Context.cpp, Source/relive_lib/Renderer/SDL2/Sdl2Context.hpp, Source/relive_lib/Renderer/SDL2/Sdl2Renderer.cpp, Source/relive_lib/Renderer/SDL2/Sdl2Renderer.hpp, Source/relive_lib/Renderer/SDL2/Sdl2Texture.cpp, Source/relive_lib/Renderer/SDL2/Sdl2Texture.hpp
Yep so here it is. :chart_with_upwards_trend:
=> SDL 2 work on beta
